# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('c_uname', models.CharField(max_length=20)),
                ('c_tel', models.CharField(max_length=20)),
                ('c_message', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
