# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('u_name', models.CharField(max_length=20)),
                ('u_pass', models.CharField(max_length=80)),
                ('u_tele', models.CharField(max_length=11)),
                ('u_recv', models.CharField(max_length=20)),
                ('u_addr', models.CharField(max_length=50)),
                ('u_recv_tele', models.CharField(max_length=11)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
