# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('act_activiting', models.BooleanField(default=False)),
                ('act_title', models.CharField(max_length=50)),
                ('act_subtitle', models.CharField(max_length=200)),
                ('act_detail', models.CharField(max_length=500)),
                ('act_image', models.ImageField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('anno_title', models.CharField(max_length=50)),
                ('anno_detail', models.CharField(max_length=200)),
                ('anno_image', models.ImageField(upload_to='images/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('cate_name', models.CharField(max_length=20)),
                ('cate_image', models.ImageField(upload_to='')),
                ('cate_desc', models.CharField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('g_name', models.CharField(max_length=30)),
                ('g_image', models.ImageField(upload_to='')),
                ('g_desc', models.CharField(max_length=100)),
                ('g_unit', models.CharField(max_length=10)),
                ('g_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('g_look', models.IntegerField(default=0)),
                ('g_cate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
