# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='cate_image',
        ),
        migrations.AlterField(
            model_name='activity',
            name='act_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
