# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20171108_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='g_florid',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='cate_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
